version: "3.7"
networks:
  catalyst_it_test:
services:
  php:
    image: jaslian/php7.4:20210222-2
    volumes:
      - .:/app/
    networks:
      catalyst_it_test: {}
  composer:
    image: composer:1.9.3
    volumes:
      - .:/app
    networks:
      catalyst_it_test: {}
  mysql:
    environment:
      KILL_PROCESS_TIMEOUT: 60
      KILL_ALL_PROCESSES_TIMEOUT: 60
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: catalyst_it_test
    restart: always
    ports:
      - 3306:3306
    image: mysql:5.7.33
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    networks:
      catalyst_it_test: {}
  adminer:
    depends_on:
      - "mysql"
    ports:
      - 8080:8080
    image: adminer:4.8.0
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    networks:
      catalyst_it_test: {}
